# Version of node
FROM node:10.7.0

# Create app directory
WORKDIR /app

# copy project files and folders to the current working directory (i.e. 'app' folder)
COPY . .

# Install dependencies
RUN npm install
