version: '3.3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm run serve
    working_dir: $PWD
    ports:
      - "8080:8080"
    expose:
      - "8080"
    volumes:
      - $PWD:$PWD
